[versions]
agp = "8.9.0"
androidGifDrawable = "1.2.28"
appcompat = "1.7.0"
countryCodePicker = "2.5.0"
circleimageview = "3.1.0"
credentials = "1.5.0"
constraintlayout = "2.2.1"
coreKtx = "1.15.0"
espressoCore = "3.6.1"
firebaseBom = "33.10.0"
glide = "4.16.0"
googleServices = "4.4.2"
googleid = "1.1.1"
hilt = "2.52"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlin = "2.1.10"
ksp = "2.1.10-1.0.31"
kotlinxCoroutinesAndroid = "1.10.1"
legacySupportV4 = "1.0.0"
lifecycleViewmodelKtx = "2.8.7"
material = "1.12.0"
navigationFragmentKtx = "2.8.9"
pinview = "1.4.4"
playServicesLocation = "21.3.0"
recyclerview = "1.4.0"
roomRuntime = "2.6.1"
volley = "1.2.1"


[libraries]
android-gif-drawable = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "androidGifDrawable" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
country-code-picker = { module = "com.hbb20:ccp", version.ref = "countryCodePicker" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
firebase-database-ktx = { module = "com.google.firebase:firebase-database-ktx" }
firebase-storage-ktx = { module = "com.google.firebase:firebase-storage-ktx" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
material = { module = "com.google.android.material:material", version.ref = "material" }
pinview = { module = "io.github.chaosleung:pinview", version.ref = "pinview" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesLocation" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleServices"}
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
